import "./globals.css";
import Link from 'next/link';
import {Metadata} from 'next';


export const metadata: Metadata = {
    title: "Web tutorials",
    description: "Generated by summmermin",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const resp = await fetch('http://localhost:9999/topics', {cache: 'no-store'}) //캐시를 쓰지않겠다는 옵션
    const topics = await resp.json()
    return (
        <html>
        <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
            {
                topics.map((topic: any) => {
                    return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
                })
            }
            {/*<li><Link href="/read/1">html</Link></li>*/}
            {/*<li><Link href="/read/2">css</Link></li>*/}
        </ol>
        {children}
        <ul>
            <li><Link href="/create">Create</Link></li>
            <li><Link href="/update/1">Update</Link></li>
            <li><input type="button" value="delete"/></li>
        </ul>
        </body>
        </html>
    );
}
